services:
  mysql_db:
    container_name: my_mysql_db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    # expose:
    #   - "3306"
    ports:
      - "${PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
